### ISSUE TITLE
brew cask slug

### ISSUE THREAD

**Issue by MoOx** [mattr-/slate#14]
I am using brew & brew cask to handle my machine setup and would like to use cask to install this version.
Do you have an idea in mind ?

FYI, I opened an issue on cask too to ask maintainers https://github.com/caskroom/homebrew-cask/issues/9648

**Comment by MoOx** [comment]
`mattr-slate` should do the thing according to the response I got from here. I will try to handle this recipe with this name if @mattr- you are ok with that.

**Comment by mattr-** [comment]
I'm cool with that. Thanks! :metal:

**Comment by MoOx** [comment]
FYI https://github.com/caskroom/homebrew-cask/pull/9756

**Comment by MoOx** [comment]
When getting merged, we should add this into the README :)
