### ISSUE TITLE
Broken on OS X Yosemite 10.10

### ISSUE THREAD

**Issue by kyldvs** [mattr-/slate#15]
Just updated my mac and slate is now broken.

I get two errors, the first is that it continually prompts me for accessibility access on launch, but it already has it: http://imgur.com/pIsUEFi

The second is that when attempting to throw a window left (alt+shift+left using my .slate.js below) I get a javascript exception: http://imgur.com/RN63acJ

This is the .slate.js file I am using: http://pastebin.com/3SiWKR0F

**Comment by mattr-** [comment]
Thanks for the great information. I hoping to get some time to look at this in the next couple of days. Feel free to ping me again if you haven't heard anything by the middle of next week.

**Comment by shan199105** [comment]
For the first error, please try to remove slate from the accessibility access by clicking the minus sign at the bottom and then add it back again to see if it fixed.

**Comment by alexilyaev** [comment]
@kyldvs Did you resolve your issue? Works for me on 10.10.3

**Comment by kyldvs** [comment]
I switched to another window manager, so not sure if it repros. I'll just close this out :)
