### ISSUE TITLE
Grid on second display does not work

### ISSUE THREAD

**Issue by awaxman11** [mattr-/slate#17]
Lot of comments over here: https://github.com/jigish/slate/issues/304#issuecomment-75927630

This one describes the problem well: 

> I installed slate lately on my laptop. I have the same issue with the grid.
> 
> The grid appears to work only on the primary monitor. From the behaviour it looks like the grid on the second monitor has no focus, and the first time I click it, it gets focus without highlighting any box of the grid, the second time I click it, the grid get's highlighted but the application I want to rearrange loses focus, and does not get rearranged. So from the behaviour it looks like it is a problem with the application's focus

**Comment by scottgerring** [comment]
Exactly the same problem here. I guess there are no workarounds or known fixes yet?

**Comment by mattr-** [comment]
I couldn't reproduce this locally. Perhaps there's something in your config that's conflicting with this? Would you mind sharing your config?

**Comment by awaxman11** [comment]
```
# This is the default .slate file.
# If no ~/.slate file exists this is the file that will be used.

config defaultToCurrentScreen true
config nudgePercentOf screenSize
config resizePercentOf screenSize

# Push Bindings
bind right:ctrl;cmd  push right bar-resize:screenSizeX/3
bind left:ctrl;cmd   push left  bar-resize:screenSizeX/3
bind up:ctrl;cmd     push up    bar-resize:screenSizeY/2
bind down:ctrl;cmd   push down  bar-resize:screenSizeY/2

# Throw Bindings
bind 1:ctrl;alt         throw 0 resize
bind 2:ctrl;alt         throw 1 resize
bind 3:ctrl;alt         throw 2 resize

# Focus Bindings
bind up:cmd;alt   focus behind
bind down:cmd;alt focus behind

# Window Hints
bind esc:cmd hint

bind 1:ctrl relaunch

bind g:cmd grid padding:3 0:6,6 1:8,6

# ======================================
# The HYPER key
# ======================================
 
alias hyper ctrl;shift;alt;cmd

# Abstract positions
alias full          move screenOriginX;screenOriginY                  screenSizeX;screenSizeY
alias lefthalf      move screenOriginX;screenOriginY                  screenSizeX/2;screenSizeY
alias righthalf     move screenOriginX+screenSizeX/2;screenOriginY    screenSizeX/2;screenSizeY
alias rightmost     move screenOriginX+screenSizeX*0.4;screenOriginY  screenSizeX*0.6;screenSizeY
alias rightless     move screenOriginX+screenSizeX*0.6;screenOriginY  screenSizeX*0.4;screenSizeY
alias leftmost      move screenOriginX;screenOriginY                  screenSizeX*0.6;screenSizeY
alias leftless      move screenOriginX;screenOriginY                  screenSizeX*0.4;screenSize 

# Nudge Bindings
# bind right:shift;alt nudge +10% +0
# bind left:shift;alt  nudge -10% +0
# bind up:shift;alt    nudge +0   -10%
# bind down:shift;alt  nudge +0   +10%
 
# Focus Bindings
bind right:${hyper}    focus right
bind left:${hyper}     focus left
bind up:${hyper}       focus up
bind down:${hyper}     focus down

# App bindings


bind right:ctrl;alt;cmd chain push right  bar-resize:screenSizeX/2 | push right  bar-resize:screenSizeX/3 | push right  bar-resize:screenSizeX/4 | push right  bar-resize:screenSizeX*2/3

bind left:ctrl;alt;cmd chain push left  bar-resize:screenSizeX/2 | push left  bar-resize:screenSizeX/3 | push left  bar-resize:screenSizeX/4 | push left  bar-resize:screenSizeX*2/3

bind up:ctrl;alt;cmd push up  bar-resize:screenSizeY/2
bind down:ctrl;alt;cmd push down  bar-resize:screenSizeY/2
bind left:ctrl;alt throw next

bind m:ctrl;alt;cmd ${full}
```

**Comment by ricardobeat** [comment]
I have the same issue with an external monitor. MBPr 13", OSX 10.10.4, laptop screen set as main. Using the grid requires an extra click that causes the app to lose focus.

![slate](https://cloud.githubusercontent.com/assets/97396/8523393/70af7fc4-23f5-11e5-92c6-b743d977c4d4.gif)

**Comment by DeathCorps69** [comment]
I'm seeing the same issue as well.

**Comment by WojtekKruszewski** [comment]
Same here.

**Comment by madeinqc** [comment]
I have the same issue. It work well when the display are side side, but as soon as my main display (the laptop one) is under the secondary screen, then it won't work anymore. Also the number for the screens are switched in the configuration.

Here's my configuration for the grid:
`bind g:cmd grid padding:5 0:8,2 1:8,3`

In side side, (laptop left, external screen right) I get a 8x2 grid on the laptop and a 8x3 grid on the external as expected and both work.
In top / bottom, (external screen at top and laptop at bottom) I get the 8x2 grid on the external screen and the 8x3 grid on the laptop screen. The grid on the laptop screen work but the grid on the external screen does not work.

**Comment by SimonSimCity** [comment]
@madeinqc thanks for providing the workaround. I rearranged my screens, so they're side-by-side. Now it works again 🎉

It's quite stressfull to remember that my second screen (virtually) is on the left side whereby it's above (physically) ... but for me, it's worth the fight. I'll get used to it.
