### ISSUE TITLE
 Crashes and hangs in accessibility code with Mavericks 

### ISSUE THREAD

**Issue by snarfed** [mattr-/slate#18]
slate crashes on me once every couple days or so on mavericks. @keithamus posted full dumps in jigish/slate#376. any idea what's going on? thanks in advance!

**Comment by snarfed** [comment]
i can reproduce this consistently by opening a movie in QuickTime Player. slate crashes as soon as QuickTime Player opens.

**Comment by mattr-** [comment]
Thanks for reporting this. I'll take a look at pulling down the JS config in that other ticket and trying to make this crash.

**Comment by snarfed** [comment]
friendly nudge. any luck reproducing this?

**Comment by mattr-** [comment]
Not yet. I had tested this in Yosemite, but I **just** realized that I was doing it with my config and not the other config from the issue. I'll give this another test and see what I find out.
