### ISSUE TITLE
Screenshots needed

### ISSUE THREAD

**Issue by anvyzhang** [mattr-/slate#21]
Maybe you should put some screenshots img to readme or wiki since there is no official website for __slate__.

**Comment by chdiza** [comment]
What would a screenshot be a screenshot of?  Slate just moves your windows around.  Maybe the "hints" feature could have a screenshot.

**Comment by MoOx** [comment]
Here are some gift that might be used (or part of them)

![icon only](http://cl.ly/image/2d1n1M3u2s2P/Screen%20Shot%202015-03-11%20at%2021.28.24.jpg)

![menu](http://cl.ly/image/3F36032c1a3T/Screen%20Shot%202015-03-11%20at%2021.28.41.jpg)

![grid](http://cl.ly/image/3K1U2Q2U1b3v/Screen%20Shot%202015-03-11%20at%2021.32.08.jpg)

![grid used](http://cl.ly/image/0R0p3v1O3j3T/Screen%20Shot%202015-03-11%20at%2021.32.10.jpg)

We can play with them and add some pieces in the README ?

**Comment by MoOx** [comment]
Maybe my screen is too big lol.

**Comment by chdiza** [comment]
The first and fourth of those don't show anything relevant to Slate.  They just show somebody's Mac.

**Comment by MoOx** [comment]
The first show the inactive Slate icon.
The fourth show that the desired grid has been used.
I am just sharing. You should be happy.
