### ISSUE TITLE
Config not being loaded

### ISSUE THREAD

**Issue by christiandalsvaag** [mattr-/slate#22]
Hi,

I have placed my config in ~/.slate.js but it seems it is not getting loaded.

Is there any way I can confirm whether it is being loaded or not? I have tried including things like alert(); and also tried making it error by adding non-keywords and syntax errors.

EDIT: I also tried 'throw test;' which according to the docs should cause the application to produce an error. I'm on Yosemite.

Any thoughts?

**Comment by mattr-** [comment]
The easiest way I know to check if the config is getting loaded is to use
one of the keybindings that you've set up in your config file and see if it
works.

**Comment by MoOx** [comment]
For js config, you can use console.log() and read them in Console.app to debug. Comment your entire file and uncomment by small pieces.

**Comment by christiandalsvaag** [comment]
Thanks. Solved. This issue was caused by a classic variation of `PEBCAK`.
