### ISSUE TITLE
Any way to change the order/layering of windows?

### ISSUE THREAD

**Issue by joshkaplan** [mattr-/slate#28]
I'd like to have a command that can send a window behind other windows. 

The use case is that I like having certain windows overlapping in a certain way. Here's an example:
![image](https://cloud.githubusercontent.com/assets/5589260/6856907/45fe14d2-d3c0-11e4-8822-0e138382d999.png)

Currently, I have a `layout` that uses the `move` command to position/size the windows correctly, and then  a `sequence` of `focus` commands to arrange them. This is not optimal because it forces each window to be focused briefly, which is conceptually inefficient and causes skype + hipchat messages in the current conversation to be marked as read. 

A better solution would be a command that could directly send a window to the back, or to a specific z-index (second from back, second from front, etc.) I don't think there's any way to do this at the moment without `focus`.

**Comment by mattr-** [comment]
This is a great idea. I'm not sure off the top of my head of a way to change the layering/ordering. I think that's behavior dependent. I'll have to look into this, but I definitely like the idea. Thanks for the suggestion! :smiley:
