### ISSUE TITLE
Change the URL that Sparkle points to for updates

### ISSUE THREAD

**Issue by mattr-** [mattr-/slate#3]
Currently, Sparkle points to the ninjamonkeysoftware.com for Slate updates. We need to figure out a new place to point it to so that Slate will autoupdate once I start releasing more updates.

**Comment by cmsj** [comment]
fwiw, github works fine for hosting. You can keep the appcast.xml in a repo and reference its "raw" URL in the Sparkle plist setting, and point the appcast at the release file hosted on github (which can be integrated into a release script using https://github.com/aktau/github-release)

**Comment by MoOx** [comment]
+1 for appcast in the repo (or on github pages).
