### ISSUE TITLE
More information about storing arbitrary data.

### ISSUE THREAD

**Issue by ProLoser** [mattr-/slate#33]
I'd like to essentially recreate stay except in a much better way. I was wondering is it possible to save arbitrary data somewhere across application launches? I'm also curious to understand how storing data as properties of window or application objects might work (or if this is flawed).

I want to essentially every time a window is opened, moved, or resized save it's location for that app+window-configuration. Then whenever an application is launched, it will go back to it's saved location, and if the screen configuration changes, I would iterate through all open windows and place them into their saved configuration for that screen setup.

**Comment by thomcom** [comment]
I'd modify the snapshots functionality, which I find to be quite unfinished as it stands. I've imagined making some similar modifications to improve Snapshot to remember which windows go where as I sometimes am running 10 separate terminals. 

```
localhost:slate thomcom$ grep -lr --include="*.m" Snapshot *
Slate/ActivateSnapshotOperation.m
Slate/Binding.m
Slate/Constants.m
Slate/DeleteSnapshotOperation.m
Slate/Operation.m
Slate/SlateAppDelegate.m
Slate/SlateConfig.m
Slate/Snapshot.m
Slate/SnapshotList.m
Slate/SnapshotOperation.m
Slate/WindowSnapshot.m
```

**Comment by ProLoser** [comment]
The issue is that you don't want to have like a snapshot of JUST what's open. I want to have snapshots saved for applications that have been previously opened and positioned that are currently closed.

**Comment by thomcom** [comment]
My imagination is that you could store every window and application in the snapshot file, and look for whether or not those windows are open when the snapshot gets loaded, modifying and tracking them if so.  Currently the SnapshotOperation completely blows away the previous snapshot each time it is run.  A fairly small modification would make it persist the snapshot as a store of window locations.

**Comment by thomcom** [comment]
Anyway the data store for Snapshots is just an NSDictionary if I remember correctly, serialized to a file.  Slate is a normal Cocoa/Obj-C application, so you can do anything to the file system you desire.

**Comment by ProLoser** [comment]
I am not a native OS dev. Honestly I was thinking of just circumventing the entire snapshot system altogether. Like creating a snapshot function in js from scratch. Just retrieve dimensions and store in a hash against app name + window configuration.

Anyway, I just need to know where/how to store the data in javascript land. Like in my .slate.js file. Can I use localStorage or something? So that across app launches it will recover this data?
