### ISSUE TITLE
OS X El Capitan Automatically Show and Hide Menu bar

### ISSUE THREAD

**Issue by caarlos0** [mattr-/slate#36]
On OS X El Capitan we can make the menu auto show and hide:

![screen shot 2015-06-21 at 11 54 24 am](https://cloud.githubusercontent.com/assets/245435/8272079/4766c432-180c-11e5-9786-b412ce7793ec.png)

But, doing that, my full screen command don't work:

```
alias full              move screenOriginX;screenOriginY                               screenSizeX;screenSizeY
bind m:${hyper} ${full}
```

![screen shot 2015-06-21 at 11 57 06 am](https://cloud.githubusercontent.com/assets/245435/8272095/a9980ed6-180c-11e5-811b-0a3e8c90891f.png)

The space of the menu is "empty"...

**Comment by mattr-** [comment]
I would that's because there's a hard coded buffer for the menu bar so that we don't hide the title bar of the window. I don't have El Capitan yet so this will have to wait until I install it after it comes out or somebody will need to open a PR.

**Comment by christiandalsvaag** [comment]
El Capitan has been out for a bit now.

Will there be a patch for this?

**Comment by ggascoigne** [comment]
El Capitan was released exactly 2 days ago, give the guy a break and don't be too impatient. :)

**Comment by hector** [comment]
+1 for this :)

@caarlos0 have you tried a temporal workaround like `screenOriginY-10`? Just to try

**Comment by caarlos0** [comment]
@hector nope, but should work...
