### ISSUE TITLE
Slate doesn't realize it can use the AccessibilityAPI

### ISSUE THREAD

**Issue by tubbo** [mattr-/slate#37]
Every time I start Slate on Yosemite 10.10.4, the following alert appears:

![screen shot 2015-07-09 at 5 12 03 pm](https://cloud.githubusercontent.com/assets/113026/8606978/ab87574c-265d-11e5-958e-46cc266b9ce1.png)

Selecting **Enable** will make everything work, this is just an annoying dialog that pops up every time I open the app.

Here's the relevant log message I saw in Console, if that helps:

```
7/9/15 5:09:42.485 PM universalAccessAuthWarn[714]: AccessibilityAPI: pid 84753, is not allowed to access the accessibility API. Path: /opt/homebrew-cask/Caskroom/mattr-slate/1.2.0/Slate.app/Contents/MacOS/Slate
```

**Comment by napcs** [comment]
@tubbo I seem to have solved this by opening the Security pref pane, unlocking the settings, unchecking and rechecking Slate's entry. I upgraded two machines from Mavericks to Yosemite last night and noticed this too.

**Comment by DeathCorps69** [comment]
@tubbo, same as @napcs . Just undo/redo you're security settings and it should work. This happened to me when i went from the jigish version to this version.

**Comment by asharpe** [comment]
I had to uncheck the existing Slate, locate the new Slate in Finder (/opt/homebrew-cask/Caskroom/mattr-slate/1.2.0) then drag the app into the allowed applications window - worked after that.
