### ISSUE TITLE
slate.screen() returns a screen with an id of -1 and no geometry.

### ISSUE THREAD

**Issue by ggascoigne** [mattr-/slate#41]
This seems to only happen reliably when slate is run for the first time after login (which is does automatically), It will happen whether there's one or more actual screens and I haven't really reproduced ti more than that.  It's fairly frustrating since it means that slate breaks on startup, but re-running it generally works correctly.

Any guesses what might be going on here?

**Comment by mattr-** [comment]
Does it happen if you restart slate after login?

Can you post your config file to a gist somewhere so I can see what's going on and test it out myself?

**Comment by ggascoigne** [comment]
No it's only on the first run.  I'll see if I can trim my config - right now it's needlessly large for a reproduction case.

**Comment by ggascoigne** [comment]
This breaks pretty reliably if it's run immediately after logging in (say as a login item).

```js
S.debug = true;

// all of the likely and unlikely screen resolutions that I might run the macbook in
function isLaptopRes(screenDescriptor) {
  return !!(screenDescriptor == '2880x1800' ||
  screenDescriptor == '2560x1600' ||
  screenDescriptor == '2048x1280' ||
  screenDescriptor == '1900x1200' ||
  screenDescriptor == '1680x1050' ||
  screenDescriptor == '1440x900');
}

function screenGeometry(rect) {
  return rect.width + 'x' + rect.height;
}

// Sadly there's no way to know whether a given screen is the laptop one or not
// but it does happen to be the only monitor I have with that particular geometry
// so we look it up based on it's size - not perfect but works for now

var detectLaptopRes = function () {
  var laptopDescriptor = '1440x900';

  var screenFunc = function (screenObject) {
    var screenDescriptor = screenGeometry(screenObject.rect());
    if (isLaptopRes(screenDescriptor)) {
      S.log("Setting default laptop size to " + screenDescriptor);
      laptopDescriptor = screenDescriptor;
    }
  };

  if (S.screenCount() == 1) {
    screenFunc(S.screen());
  } else {
    S.eachScreen(screenFunc);
  }
  return laptopDescriptor;
};

var name = detectLaptopRes();
S.log('detected ' + name);
```

This is trimmed out of a much larger script.

Interestingly if I simplify that last but to not special case the single screen mode then I think that it's actually working - though I'll have to try it for a while longer to know for sure.

**Comment by mattr-** [comment]
Cool. Thanks. I'll try to take a look soon. It'll probably take me a bit to get a clean reproduction environment set up.
