### ISSUE TITLE
Sync config across multiple macs?

### ISSUE THREAD

**Issue by shobhitg** [mattr-/slate#43]
Hi,

I am looking for a a recommended way to safely sync .slate file across multiple macs.
I usually use dropbox for all my syncing needs. 

I suppose since reload in slate happens only on demand, there should not be any issues related to bad state due to concurrency.
I guess I should be able to setup sync, as long as I can tell my slate to load config from a different place. How can I change location of config file from ~/.slate to ~/Dropbox/.slate ?

thanks.

**Comment by MoOx** [comment]
I use a symlink for my .slate.js and it's working.

**Comment by mattr-** [comment]
I recommend using a symlink for this as well.
