### ISSUE TITLE
After toggle key-combination or multiple keystrokes.

### ISSUE THREAD

**Issue by mhavo** [mattr-/slate#44]
# Idea

I think Slate should provide same way to arrange and resize windows as tmux (combination of keys after toggle) **or** kind of idea of language to manipulate windows - like VIM does for text objects: In series of keystrokes.

This way there is much less possibilities to interfere shortcuts in other programs and it would be much easier to remember how to command window-manager.
## TMUX -style

Slate should give opportunity to use **combination** of keys after toggle:

``` bash
# ctrl-a to toggle to slate-mode and then pushing with ALT pushed plus arrow 
bind alt,right:ctrl,a:toggle resize +10% +0 to resize screen.
```
## VIM -style

``` bash
# first initiate slate-mode, then m as move, w-window (taken from hint reffered as '&' 
# in here.) to screen 1 in using layout 1-main.
bind move,&,1:ctrl,a:toggle  throw 1 ${1-main} 
# push window by given rules or to some alias.
bind p,.:ctrl,a:toggle push right bar-resize:screenSizeX/2  
```

**Comment by ggascoigne** [comment]
Not quite the same thing but I use https://github.com/lunixbochs/reslate.git and rebind a hyper key, this take all of my window management keys out of the "clash" range.  Really works rather nicely.

**Comment by m812215** [comment]
I will look at that, thank you. Better yet Slate should introduce global modal-change - not per key - but global change like in Karabiner VIM/VI -modal changes and show with popup that special mode.
