### ISSUE TITLE
On ElCap, the corner/push operations can't push a window all the way to the righthand edge

### ISSUE THREAD

**Issue by chdiza** [mattr-/slate#50]
On 10.11.1, the corner and push operations are unable to move a window flush to the righthand edge of the monitor.  There is always a gap of about five or six pixels.  This was not the case on Yosemite or earlier.  And no such issue exists regarding the left-hand edge of the screen.

There is an issue with the top edge of the screen (persistent one-pixel gap), but this is an already-reported Apple bug and has nothing to do with slate.

**Comment by mattr-** [comment]
Could you provide a screenshot please? I'm not running ElCap yet for a variety of other reasons and it never hurts to have a static example. :smiley:

**Comment by chdiza** [comment]
This is a screenshot of the northeast corner of the screen, which contains a Safari window.  You can see the Notification Center icon and Safari's NewTab icon.  You can also see, along the righthand edge, several turquoise pixels of my desktop.
![screenshot](https://cloud.githubusercontent.com/assets/3311113/10992054/4cde48be-8430-11e5-9949-9064af6dc4d6.png)

**Comment by lochstar** [comment]
I am running El Cap and the push operation is correctly positioning the window right on the edge of the screen.

**Comment by ts** [comment]
For what it's worth, I've noticed this issue with various recent versions of OS X and Slate.
