### ISSUE TITLE
Move Javascript configuration documentation from the old wiki to a doc in the `doc` folder

### ISSUE THREAD

**Issue by mattr-** [mattr-/slate#52]
@smammy's doc enhancements in #51 made me realize that the Javascript configuration is currently in a wiki page in the old jigish/slate repository. It would be awesome if somebody could move that over from the wiki to a markdown document in this repository that lives in the `doc` folder.

**Comment by smammy** [comment]
Current status:
* Events - TODO.
* Example Configs - TODO, copy to `mattr-/slate/wiki` or create new `example` dir?
* Keystrokes - TODO, most info is in `keys.md` and `directive-bind.md`, but some info about syntax in JS config may need to be added to `doc` dir.
* Operations - TODO.
* Application-Object - DONE.
* Defaults - DONE.
* Expressions - DONE, see #53.
* Global Configs - DONE.
* Installation instructions - DONE.
* JavaScript Config - DONE.
* Layouts - DONE.
* Screen-Object - DONE.
* Window-Object - DONE.
