### ISSUE TITLE
Move Expressions documentation from the old wiki to the repo

### ISSUE THREAD

**Issue by mattr-** [mattr-/slate#53]
@smammy's doc enhancements in #51 made me realize that the Expressions documentation is also currently in a wiki page in the old jigish/slate repository. It would be awesome if somebody could move that over from the wiki to a markdown document in this repository that lives in the doc folder.

Also need to double check that the information we have in the docs about Expressions isn't already in our `doc` folder, making the wiki redundant.

**Comment by smammy** [comment]
Also in `jigish/slate/wiki`:
* Application-Object - add to `doc` dir
* Defaults - add to `doc` dir
* Events - add to `doc` dir
* Example Configs - copy to `mattr-/slate/wiki` or create new `example` dir?
* Expressions - already covered in `configuration.md`
* Global Configs - already added to `directive-config.md`
* Installation instructions - superseded by `installation.md`
* JavaScript Config - see #52 
* Keystrokes - most info is in `keys.md` and `directive-bind.md`, but some info about syntax in JS config may need to be added to `doc` dir
* Layouts - add to `doc` dir
* Operations - add to `doc` dir
* Screen-Object - add to `doc` dir
* Window-Object - add to `doc` dir

**Comment by mattr-** [comment]
:sob:​ :sob: :sob:

**Comment by smammy** [comment]
I'll probably take care of this now that I've started. :confused:

**Comment by mattr-** [comment]
Thanks so much for your help with the documentation. I've added you as a contributor to the repo. Feel free to push branches here. Keep opening PRs but feel free to merge them yourself.

**Comment by smammy** [comment]
Expressions documentation in wiki was redundant to what we already had in `doc/configuration.md`. I'm closing this an am going to do the rest of the work in #55.

**Comment by mattr-** [comment]
:+1: Thanks!
