### ISSUE TITLE
On El Capitan, changing focused app can change Spaces

### ISSUE THREAD

**Issue by NateEag** [mattr-/slate#54]
I recently upgraded straight from Snow Leopard to El Capitan.

[My Slate config](https://github.com/NateEag/dotfiles/blob/master/src/slate) binds several different keys to the 'focus' operation.

Under Snow Leopard, this worked exactly like I expected.

In El Capitan (and possibly preceding versions), focusing an application can cause me to jump between spaces, especially if there is no open window for the app in the current space.

I have unchecked System Preferences > Mission Control > "When switching to an application, switch to a Space with open windows for the application", and Command-Tab switching behaves the way you'd expect.

It looks almost like Slate's trying to restore the last-used window in the focused app, regardless of my current space. I don't know anything about Slate's internals, so I have no idea if that's remotely plausible or not.

**Comment by mattr-** [comment]
Slate doesn't have any support for Mission Control/Spaces/Expose/whatever Apple is calling it this release, so I wouldn't expect something that Slate is doing to affect this, but I'll have to dig deeper into this.

**Comment by NateEag** [comment]
Okay. If Slate does nothing with Spaces, I bet the (better) behavior I'm used to was just a coincidence, and the changes to multiple desktops in El Cap just happen to break it.

Thanks.

**Comment by NateEag** [comment]
Historical note: I've finally started the move from Slate to [Hammerspoon](https://www.hammerspoon.org), and focusing apps with the standard Hammerspoon technique does not have this effect. Currently running High Sierra, where I still saw this behavior with Slate.

I know no one maintains Slate any more - I just felt the need to share the information, because it's a little more data about the problem, irrelevant though the problem itself now is.
