### ISSUE TITLE
Is there a way to don't move window across monitors ?

### ISSUE THREAD

**Issue by jeanlaurent** [mattr-/slate#57]
I hooked a monitor to my laptop.

Let's say I got the minimal configuration here :
```
config defaultToCurrentScreen true
bind 1:alt,cmd move 0;0 screenSizeX/2;screenSizeY
```
With my current understanding, should make the current window goes to the top left and take half the screen size whenever I press ALT-CMD-1

it works flawlessly on the monitor or when I am using only the laptop without the external monitor ( the one with the menu bar in the mac preference panel )

But If I do the same thing on a window on the laptop screen while having the monitor hooked to the laptop, then the window is moved on the monitor...

I played quite a bit with the various combination, but can I make the same keystroke work and that it apply it to the current screen only ?

**Comment by mattr-** [comment]
This will do what you want:
```
move screenOriginX;screenOriginY screenSizeX/2;screenSizeY
```

`screenOriginX` and `screenOriginY` take into account the current screen that you're on. Slate maps all the screens based on how they're presented by OS X and so `0;0` always ends up being the on the primary display (which is the display with the menu bar on it).
