### ISSUE TITLE
operation.show - open one application if it is not opened yet

### ISSUE THREAD

**Issue by zfdang** [mattr-/slate#59]
now the show operation only show application which is open. if the app was not opened yet, you have to open it manually. is it possible to change this operation, or provide another operation named "open"?

**Comment by mattr-** [comment]
Possibly. Slate has traditionally only worked with open applications.






On Fri, Jan 15, 2016 at 1:22 AM -0800, "Zhengfa Dang" <notifications@github.com> wrote:












now the show operation only show application which is open if the app was not opened yet, you have to open it manually is it possible to change this operation, or provide another operation named "open"?
