### ISSUE TITLE
Message App (Nachrichten) not working

### ISSUE THREAD

**Issue by thepill** [mattr-/slate#62]
hi - at first: great work!

But im having a little problem (i´m new to slate btw.). following code is working for safari but my message app (german: Nachrichten) isn´t moving. I tried also "Messages" and "Nachrichten.app" but no luck.

`var layoutMac = S.layout("layoutMac", {
	"Nachrichten" :{
		"operations" : [moveFull]
	},
	"Safari" :{
		"operations" : [moveFull]
	}
});`

`var moveFull = S.operation("move", {
	"x" : "screenOriginX",
	"y" : "screenOriginY",
	"width" : "screenSizeX",
	"height" : "screenSizeY"
});`

**Comment by xkonni** [comment]
did you check the actual class of that window? slate does have that in the
menu iirc (at work right now, using linux)

**Comment by Pr1m-e** [comment]
Application: Nachrichten
  Window: 'Nachrichten'
    Screen ID (Left to Right): 0
    Size: (720, 436)
    Top Left: (screenOriginX+0, screenOriginY+410)

**Comment by thepill** [comment]
re-created the .slate.js file and it works :/
