### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by al3xandru** [mattr-/slate#66]
There have been more than 30 commits and over 1 year since the last release. Even if these changes are minimal I'm sure many will be happy to have a new build.

**Comment by mattr-** [comment]
:soon: :smiley:

**Comment by napcs** [comment]
When will soon be now? :)

**Comment by yn5** [comment]
@napcs @al3xandru For now you can clone/download the master branch and compile it yourself with Xcode:
Open Slate.xcodeproj, build the project (`CMD+D`), right click `Slate.app` in the `Projects` Group (or "folder") in Xcode's Project navigator and click `Show in Finder`. Right click the `Slate.app` (symlink) shown in Finder and click `Show original` and copy the actual `Slate.app` which is that gets shown to your `/Applications` folder.

**Comment by luisdavim** [comment]
Almost another year has passed and yet no release. Is this still being maintained?

**Comment by mattr-** [comment]
No. It's not really. I've moved most of my window automation over to Hammerspoon. I'l post something here in the README soon™.
