### ISSUE TITLE
Provide better facilities for debugging the dynamic configuration

### ISSUE THREAD

**Issue by mattr-** [mattr-/slate#68]
The discussion in #67 exposed a miss in how users can debug Slate's dynamic configuration if something goes wrong and the functionality in that file fails to work after loading the config. We should figure out if the troubleshooting experience can be made better and if so, what that better experience would look like.

**Comment by therealplato** [comment]
logging to /var/log/slate.log would be nice. i have no feedback about javascript errors. slate.log("foo") does not show up in /var/log/system.log so i have no idea how i can add debug statements to fix my code

**Comment by amjames** [comment]
@therealplato `slate.log("foo")` will appear in the OS X console  (`/Applications/Utilities/Console.app`) under all messages, but I can't seem to find a file or any other tab where these messages appear. They do all register as from `Slate:` so putting "Slate" in the filter/search field will isolate those messages from others. If you have the filter set to "Slate" and reload slate you should see something like this:

`4/14/16 2:43:35.994 PM Slate: JS INIT FINISHED`

These messages don't seem to be saved to a file like other apps, so they have limited usefulness
