### ISSUE TITLE
resize not working properly after pushed to right

### ISSUE THREAD

**Issue by sinofool** [mattr-/slate#70]
Reproduce:
1. Use default config.
2. Cmd+Ctrl+Right to push current window to right 1/3.
3. Ctrl+Alt+Left, expected to enlarge current window at left, but not.

If using Alt+Left resize current window after step 2, then step 3 works as expected.
(But current window bottom border detached from screen border.)

The same mirrored operation works perfectly at left edge.

**Comment by mattr-** [comment]
Do you have your dock on the right edge?​

**Comment by sinofool** [comment]
Yes, dock on the right edge with auto hide on.

**Comment by sinofool** [comment]
I moved the dock to bottom and it's still the same.

**Comment by sinofool** [comment]
If I moved the "resize" code after "move", it works.
It looks like "AXUIElementSetAttributeValue" cannot resize a window to outside screen.

I am not sure if this change will affect other behaviors.

**Comment by sinofool** [comment]
PR #72 merged, closing this issue.

**Comment by PaulDapolito** [comment]
Issue still exists, please see PR #75.
