### ISSUE TITLE
Resize from Left Edge not responding or responding with 1% changes

### ISSUE THREAD

**Issue by Nostromos** [mattr-/slate#71]
Hey All, 

Chrome Version 49.0.2623.87 (64-bit) on macbook pro running  ElCap 10.11.4. 

I've having trouble with resizing from left side/corner (aka Control+Alt+Left Arrow). It will work sporadically and then stop. I've tried it on another mbp running the same and I'm getting similar behavior but unable to reproduce. 

Steps that usually lead to reproducing behavior:
1. Focus on any window
2. Control + Alt + Right Arrow to resize -10% from the left.
3. Control + Alt + Left Arrow to resize +10% from the left fails to work. Sometimes it will work once or twice and then stop working entirely.

**Comment by sinofool** [comment]
I have the similar issue #70 and opened a PR earlier.
Would you please try if it fixed your issue too?

If you don't want to compile the whole app, here is a binary: https://sinofool.net/dl/Slate.zip

**Comment by Nostromos** [comment]
Apologies for the late reply. Works great so far. All I need to do is close this issue out, right?
