### ISSUE TITLE
Is there ANY reason why this should not work correctly?

### ISSUE THREAD

**Issue by tofagerl** [mattr-/slate#73]
This is two rules I've set up for media players. Plex and movist, basically, but the bug/misconfiguration happens with all apps. 
```
bind 9:shift,cmd,. move screenSizeX-800;screenSizeY-450-22 800;450+22
bind 8:shift,cmd,. move screenSizeX-600;screenSizeY-450-22 600;450+22
```
As read, this rule should place the window in either a 16x9 or a 4x3 window (plus menubar) at the lower right end of the screen so that I can watch mah stories. But instead it places it like the image below, where there is a  noticable gap at the bottom, and it is ruining my day :|
![Image worth 1k words]
(https://www.dropbox.com/s/edhfax9msk7su4w/Screenshot%202016-04-07%2019.31.21.png?dl=1)
There is a HUGE chance this is due to a misconfiguration on my part, of course, but I have no one to ask, so I thought I might as well place this concern on your shoulders, GitHub community.

**Comment by mattr-** [comment]
I've not had good luck just using the sizes as the top left coordinates of a window. You may want to try adding the window size as an offset from the screen origin, like so:
```
bind 9:shift,cmd,. move screenOriginX+(screenSizeX-800);screenOriginY+(screenSizeY-472) 800;472
bind 8:shift,cmd,. move screenOriginX+(screenSizeX-600);screenOriginY+(screenSizeY-472) 600;472
```

If you try doing it that way, does it work out better?

**Comment by tofagerl** [comment]
Yes it does, thanks a lot :)

I wonder why that is... 
Should I move all my working bindings to Origin instead of Size as well?

**Comment by mattr-** [comment]
If your other bindings work, I don't see a reason to change them, but I'd start newer bindings with the origin all the time.

Glad it's working for you! :+1:

**Comment by tofagerl** [comment]
I tried a bit. Some got rid of the gap between the window border and the screen edge, but others developed this very problem. In the end I went with the better solution in every case, which was pretty individual. I'm sure there's logic to it, but I can't see it yet. 

In any case, all bindings now work :)
