### ISSUE TITLE
Frequently can't move JetBrains IDE Window

### ISSUE THREAD

**Issue by joshkaplan** [mattr-/slate#74]
I am frequently unable to move or resize the main window of PHPStorm and other Jetbrains IDEs. This seems to happen after a period of usage. Restarting the app causes the issue to disappear.

Note: these are Java applications, not sure if that is relevant.

**Details:**
When the problem occurs, I cannot use the `resize`, `throw`, `move`, or any other operation that manipulates the main PHPStorm window. `focus` operations continue to work on this window. All operations continue to work normally for other windows.

I am on the latest release of slate, 1.2.0.

**Possible Causes:**
I have been unable to isolate the exact cause. I have tested most operations I regularly do with slate (disconnecting / reconnecting monitors, saving/restoring layouts, moving stuff around, switching applications), but cannot recreate the issue perfectly. Having multiple project windows open seems to cause issues, but the problem happens even without multiple project windows.

**Comment by tedpearson** [comment]
Same here with IntelliJ. :)
