### ISSUE TITLE
Support spaces

### ISSUE THREAD

**Issue by MoOx** [mattr-/slate#8]
Lots of information here https://github.com/jigish/slate/issues/78

**Comment by KMontag42** [comment]
all of my :+1:

**Comment by sdegutis** [comment]
To summarize all that we've learned (context: I'm another WM author):

- Apple has provided no public API for Spaces
- Some people reverse-engineered a private API for Spaces
- That private API stopped working at OS X 10.9 and still doesn't work on 10.10

The only options moving forward are:

- File a bug ("radar") with Apple asking for a public Spaces API
- Reverse-engineer any private Spaces API for 10.10 and possibly also 10.9
- Abandon all hope and move to Linux *(shudder)*

There has been some work done on the second option, reverse engineering the API for newer OS versions:

Here are [https://github.com/sdegutis/mjolnir/issues/297](some reverse-engineering efforts documented in real-time).

Here's another quote from @puffnfresh on this issue:

> class-dump will almost certaintly get you nowhere. Previous to Mavericks all space handling was done in CoreGraphics. It probably still is, so you should be able to get somewhere by dumping the symbols:
> 
> `nm /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics | grep "\b_CG"`
>
> Attaching a debugger will probably cause your desktop to completely halt, so it's not a great idea unless you're doing it over ssh. I'm thinking that something like dtrace would be a much better idea.
> 
> Looks like Mavericks runs a process at /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/Resources/WindowServer - I think that might be the thing you want to attach to.
> 
> I also recommend using http://www.hopperapp.com/ to figure out the control flow and types of arguments.
> 
> Good luck!

**Comment by puffnfresh** [comment]
I started to do option 2 but failed pretty badly. I decided to move to option 3 a few months ago.

**Comment by sdegutis** [comment]
@puffnfresh some days I do lean towards that myself.

**Comment by promorphus** [comment]
Any progress or updates on this?

**Comment by mattr-** [comment]
Nope. There's only so much time in the day and I can't spend it all on Slate.

**Comment by promorphus** [comment]
No worries! I was going to attempt to look into this myself, and didn't want to duplicate the effort if it was already solved / looked at.

**Comment by donners** [comment]
Wow, a few hours ago I thought to myself "I need a WM to save the state of all my spaces", assuming it would be no big deal.

I finally ended up here at a complete dead end! Good luck with a solution, I'll be keeping an eye out.

**Comment by alexilyaev** [comment]
@MoOx @sdegutis Hey guys, is there any progress with this issue?
At least from an API perspective or other solutions that's available (even if hacky)?

**Comment by sdegutis** [comment]
Absolutely nothing has changed.

**Comment by alexilyaev** [comment]
@sdegutis Do we have a link to an open Apple ticket or something?

**Comment by sdegutis** [comment]
I've given up on filing tickets with Apple years ago. Adding these kind of features is not in their best financial interests. Their job is to keep the UI/UX smooth and non-customizable.

**Comment by oskarols** [comment]
I don't understand why anyone would need spaces anymore.

If you have the capability to switch between a constellation of applications (via a predefined layout, grid etc), and even to snapshot the current stack of windows — what does Spaces bring to the table?

**Comment by sdegutis** [comment]
My guess: Some apps look slightly different in Full Screen (i.e. Spaces) mode. But still, I agree with you.

**Comment by alexilyaev** [comment]
@oskarols Mostly full screens apps, like watching a video in full screen and moving to a different space without breaking the full screen.

**Comment by gbvb** [comment]
From what I am seeing, the only way to support spaces would be to fake it like Amethyst does. I dont know if that would be sufficient or not.  https://github.com/ianyh/Silica/blob/master/Silica/SIWindow.m has the code to move a window to a space as long as you have key shortcuts assigned to spaces in Mission Control. 
If someone is so inclined, they can look at moveToSpaces() method to mimic the behavior. It works fairly well with my usage. Or you can use Amethyst and Slate together :)

**Comment by SebastienElet** [comment]
I would love this feature :+1:
