### ISSUE TITLE
Mouse Cursor Object

### ISSUE THREAD

**Issue by TabSel** [mattr-/slate#9]
Would it be, or is it already possible to get/set mouse cursor position, and to be notified upon mouse events?

**Comment by goldencut** [comment]
I'm not sure where you're going with this but what I would like to see is mouse control: you drag a window to a location (screen corners, screen sides, dock etc) and release, and window will snap to some defined size and position. Is that too utopian? It might be urban legend but I've heard that some other, awful, lame OS might be able to already do this...
